In [3]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import osmnx as ox

# handle filepaths
import os
import configparser

In [4]:
#set filepaths
project_root = os.path.abspath(os.getcwd())
root = os.path.abspath(os.path.join(os.getcwd(), '..', '..'))
config_file =  os.path.join(root, 'config.cfg')

# geodata for shapefiles
config = configparser.ConfigParser()
config.read(config_file)
gdata_root = config['geodata']['path']

## Load data

### London shapefiles

In [5]:
# get London borough shapefile
london = gpd.GeoDataFrame.from_file(os.path.join(gdata_root, 'london-shapefiles\\London_Borough_Excluding_MHW.shp'))
london = london.to_crs('EPSG:4326')

# convert to correct CRS to have units in meters in the UK
_crs = "EPSG:32630"
london_reprojected = london.to_crs(_crs)

### Funding bids

In [106]:
funding = pd.read_csv("transport_bids_by_borough.csv", skiprows=2, usecols=[0,1,2,3], header=None, names=["GSS_CODE","borough", "cycling_bid", "cycling_funding"])

### TfL cycle routes

In [56]:
# load TFL cycle routes
tfl_cycle_routes = gpd.GeoDataFrame.from_file('TfL_CycleRoutes.json')

### OSM data

Gets data from OSM using `osmnx` and save in csv files to load in for future runs

#### OSM road stats

In [ ]:
road_stats = {"NAME": [],
              "OSM_street_length_total": []
              }

for i in range(len(london)):
    roads = ox.graph_from_polygon(london["geometry"][i],network_type='drive')
    basic_stats = ox.stats.basic_stats(roads, area=None)
    road_stats["NAME"].append(london["NAME"][i])
    road_stats["OSM_street_length_total"].append(basic_stats["street_length_total"])
    
road_stats_df = pd.DataFrame.from_dict(road_stats)

In [6]:
# save output
road_stats_df.to_csv("OSM_road_stats_by_borough.csv", index=False)

In [72]:
# load preprocessed csv file
road_stats_df = pd.read_csv("OSM_road_stats_by_borough.csv")

#### OSM cycle routes

Useful code in [this tutorial](https://williamthyer.github.io/posts/2021/4/bike_networks/) and 
the [original Github Thread](https://github.com/gboeing/osmnx/issues/151)

Example notebooks in docs: https://github.com/gboeing/osmnx-examples/blob/main/notebooks/08-custom-filters-infrastructure.ipynb

In [6]:
# Configuring osmnx
ox.settings.useful_tags_way += ["cycleway"]

def get_cycleways_polygon(polygon):    
    # Querying for roads and bike trails
    cycleways = ox.graph_from_polygon(polygon, network_type='bike', simplify=True)
    
    # Finding all non-cycleways in the network
    non_cycleways = [(u, v, k) for  u, v, k, d  in  cycleways.edges(keys=True, data=True) if  not ('cycleway'  in  d  or  d['highway']=='cycleway')]
   
    # Remove non-cycleways and isolated nodes
    cycleways.remove_edges_from(non_cycleways)
    cycleways = ox.utils_graph.remove_isolated_nodes(cycleways)
    
    return cycleways

In [13]:
cycleways_df = []
cycle_stats = {"NAME": [],
              "OSM_cycleways_length_total": [],
              }

for i in range(len(london)):
    # get cycleways for each borough
    polygon = london["geometry"][i]
    cycleways = get_cycleways_polygon(polygon)

    # get basic stats
    basic_stats = ox.stats.basic_stats(cycleways, area=None)
    cycle_stats["NAME"].append(london["NAME"][i])
    cycle_stats["OSM_cycleways_length_total"].append(basic_stats["street_length_total"])

    # turn cycleways into gdf
    cycleways_df_single = ox.utils_graph.graph_to_gdfs(cycleways, nodes=False, edges=True)
    cols = ['highway',  'cycleway', 'length', 'geometry']
    cycleways_df_single = cycleways_df_single[cols].reset_index(drop=True)
    cycleways_df_single["NAME"] = london["NAME"][i]
    cycleways_df.append(cycleways_df_single)

cycleways_df = pd.concat(cycleways_df, ignore_index=True)
cycleways_stats_df = pd.DataFrame.from_dict(cycle_stats)

In [11]:
# save outputs
cycleways_df = cycleways_df.rename_geometry('WKT')
cycleways_df.to_csv("OSM_cycleways_by_borough.csv", index=False)
cycleways_stats_df.to_csv("OSM_cycleways_stats_by_borough.csv", index=False)

In [71]:
# load preprocessed csv file
cycleways_stats_df = pd.read_csv("OSM_cycleways_stats_by_borough.csv")
cycleways_gdf = gpd.read_file("OSM_cycleways_by_borough.csv")
cycleways_gdf = cycleways_gdf.set_crs('EPSG:4326')

## Process data

In [108]:
gdf = london[['NAME', 'GSS_CODE', 'HECTARES', 'NONLD_AREA', 'ONS_INNER', 'geometry']]

### Funding

In [109]:
gdf = pd.merge(gdf, funding[["GSS_CODE","cycling_bid", "cycling_funding"]], left_on="GSS_CODE", right_on="GSS_CODE", how="left")

### OSM stats

In [110]:
gdf = pd.merge(gdf, road_stats_df, left_on="NAME", right_on="NAME", how="left")
gdf = pd.merge(gdf, cycleways_stats_df, left_on="NAME", right_on="NAME", how="left")

### TfL routes length

In [111]:
tfl_cycle_routes_total_length = []
tfl_cycle_routes_open_length = []
tfl_cycle_routes_planned_length = []

for i in range(len(london)):
    routes_clipped = gpd.clip(tfl_cycle_routes, london["geometry"][i], keep_geom_type=True)
    tfl_cycle_routes_total_length.append(routes_clipped["Shape_Leng"].sum())

    open_routes_clipped = gpd.clip(tfl_cycle_routes[tfl_cycle_routes["Status"]=="Open"], london["geometry"][i], keep_geom_type=True)
    tfl_cycle_routes_open_length.append(open_routes_clipped["Shape_Leng"].sum())

    planned_routes_clipped = gpd.clip(tfl_cycle_routes[tfl_cycle_routes["Status"]!="Open"], london["geometry"][i], keep_geom_type=True)
    tfl_cycle_routes_planned_length.append(planned_routes_clipped["Shape_Leng"].sum())

# add to gdf
gdf.loc[:,"tfl_cycle_routes_total_length"] = tfl_cycle_routes_total_length
gdf.loc[:,"tfl_cycle_routes_open_length"] = tfl_cycle_routes_open_length
gdf.loc[:,"tfl_cycle_routes_planned_length"] = tfl_cycle_routes_planned_length

### Calculate ratios

In [112]:
gdf

,NAME,GSS_CODE,HECTARES,NONLD_AREA,ONS_INNER,geometry,cycling_bid,cycling_funding,OSM_street_length_total,OSM_intersection_count,OSM_cycleways_length_total,tfl_cycle_routes_total_length,tfl_cycle_routes_open_length,tfl_cycle_routes_planned_length
0,Kingston upon Thames,E09000021,3726.117,0.000,F,"POLYGON ((-0.33066 51.32901, -0.33057 51.32909...",0,0,348442.337,2086,36092.105,17985.913505,16381.641919,1604.271586
1,Croydon,E09000008,8649.441,0.000,F,"POLYGON ((-0.06399 51.31864, -0.06405 51.31861...",0,80,794682.782,4630,38650.448,0.000000,0.000000,0.000000
2,Bromley,E09000006,15013.487,0.000,F,"POLYGON ((0.01216 51.29960, 0.01199 51.29979, ...",21,5,911900.591,4699,38665.652,4876.804524,0.000000,4876.804524
3,Hounslow,E09000018,5658.541,60.755,F,"POLYGON ((-0.24454 51.48870, -0.24466 51.48868...",804,225,528340.936,3204,68563.904,19526.447194,14234.219367,5292.227827
4,Ealing,E09000009,5554.428,0.000,F,"POLYGON ((-0.41181 51.53408, -0.41186 51.53413...",540,115,593591.492,3535,75333.218,44393.719253,30877.084811,13516.634442
5,Havering,E09000016,11445.735,210.763,F,"POLYGON ((0.15872 51.51219, 0.15873 51.51224, ...",200,50,700001.907,3676,51563.295,0.000000,0.000000,0.000000
6,Hillingdon,E09000017,11570.063,0.000,F,"POLYGON ((-0.40405 51.61318, -0.40386 51.61230...",165,165,821816.786,4620,67717.875,23259.475437,23259.475437,0.000000
7,Harrow,E09000015,5046.330,0.000,F,"POLYGON ((-0.40405 51.61318, -0.40318 51.61318...","1,050",235,466584.027,2780,24093.747,0.000000,0.000000,0.000000
8,Brent,E09000005,4323.270,0.000,F,"POLYGON ((-0.19654 51.52766, -0.19682 51.52774...",0,0,493454.700,2997,26531.182,35285.383766,27212.605551,8072.778215
9,Barnet,E09000003,8674.837,0.000,F,"POLYGON ((-0.19987 51.67017, -0.19968 51.66986...",809,80,811565.232,4614,41412.155,1407.774758,0.000000,1407.774758
10,Lambeth,E09000022,2724.940,43.927,T,"POLYGON ((-0.12843 51.48505, -0.12841 51.48506...","1,371",345,396215.874,2839,30053.218,48066.165137,41139.494133,6926.671005
11,Southwark,E09000028,2991.340,105.139,T,"POLYGON ((-0.10890 51.50844, -0.10887 51.50845...","2,695","1,295",390913.454,3029,66280.285,56766.967581,49627.220928,7139.746652
12,Lewisham,E09000023,3531.706,16.795,T,"POLYGON ((-0.03239 51.49306, -0.03237 51.49303...",0,0,452894.312,2916,33734.360,56903.253583,39938.019653,16965.233930
13,Greenwich,E09000011,5044.190,310.785,F,"MULTIPOLYGON (((-0.02482 51.48555, -0.02477 51...",0,40,547283.825,3571,75766.830,52699.694763,41850.245939,10849.448823
14,Bexley,E09000004,6428.649,370.619,F,"POLYGON ((0.12024 51.51145, 0.12162 51.51181, ...",100,30,577497.521,3381,41832.815,20122.921976,20122.921976,0.000000
15,Enfield,E09000010,8220.025,0.000,F,"POLYGON ((-0.10578 51.69188, -0.10554 51.69187...","2,336","1,286",659515.520,3993,91652.073,45773.674164,35655.363632,10118.310532
16,Waltham Forest,E09000031,3880.793,0.000,F,"POLYGON ((0.01927 51.60822, 0.01933 51.60807, ...","4,270",610,424794.216,2583,92904.043,40238.706013,37864.819511,2373.886502
17,Redbridge,E09000026,5644.225,2.300,F,"POLYGON ((0.06939 51.54413, 0.06913 51.54418, ...",800,150,556917.868,3147,41081.036,11645.433933,10336.134757,1309.299176
18,Sutton,E09000029,4384.698,0.000,F,"POLYGON ((-0.15654 51.32151, -0.15863 51.32398...",688,475,421749.372,2559,29713.419,0.000000,0.000000,0.000000
19,Richmond upon Thames,E09000027,5876.111,135.443,F,"POLYGON ((-0.32171 51.46541, -0.32170 51.46536...",640,300,423855.463,2584,63837.605,14678.243368,10477.131434,4201.111934
20,Merton,E09000024,3762.466,0.000,F,"POLYGON ((-0.13429 51.39093, -0.13435 51.39089...",260,160,377941.667,2308,39318.697,17335.230332,15287.964471,2047.265861
21,Wandsworth,E09000032,3522.022,95.600,T,"POLYGON ((-0.22340 51.47152, -0.22325 51.47146...",670,100,452122.586,3105,40859.735,29899.431191,29899.431191,0.000000
22,Hammersmith and Fulham,E09000013,1715.409,75.648,T,"POLYGON ((-0.24454 51.48870, -0.24458 51.48879...","1,085",300,219241.813,1549,19852.584,66238.123146,54738.491624,11499.631522
23,Kensington and Chelsea,E09000020,1238.379,25.994,T,"POLYGON ((-0.18386 51.47742, -0.18401 51.47753...",280,225,207224.782,1666,11720.559,72158.992276,56724.317124,15434.675152
24,Westminster,E09000033,2203.005,54.308,T,"POLYGON ((-0.14998 51.48549, -0.15006 51.48590...","1,438",519,349937.778,2871,39928.627,77418.010063,68800.156479,8617.853584
25,Camden,E09000007,2178.932,0.000,T,"POLYGON ((-0.14239 51.56912, -0.14248 51.56902...","5,250","1,475",274495.358,1976,46633.302,54097.132362,49731.824062,4365.308301
26,Tower Hamlets,E09000030,2157.501,179.707,T,"POLYGON ((-0.07935 51.50784, -0.07932 51.50791...",NaN,NaN,317708.433,2553,48062.931,44671.393873,39705.126509,4966.267364
27,Islington,E09000019,1485.664,0.000,T,"POLYGON ((-0.13837 51.55686, -0.13849 51.55701...","1,149",455,228593.176,1765,21062.669,56091.304861,51488.490814,4602.814048
28,Hackney,E09000012,1904.902,0.000,T,"POLYGON ((-0.09764 51.57365, -0.09753 51.57368...","3,017",460,258445.714,1891,53428.297,64221.984888,51815.137342,12406.847546
29,Haringey,E09000014,2959.837,0.000,T,"POLYGON ((-0.09764 51.57365, -0.09777 51.57362...",500,50,357125.819,2354,43399.234,34697.481083,30660.566114,4036.914969
30,Newham,E09000025,3857.806,237.637,T,"MULTIPOLYGON (((0.07551 51.52982, 0.07549 51.5...","3,615",315,466096.773,3213,99534.418,50706.466529,47532.014607,3174.451922
31,Barking and Dagenham,E09000002,3779.934,169.150,F,"MULTIPOLYGON (((0.07319 51.52937, 0.07319 51.5...",555,230,368323.703,2274,50592.628,29792.217946,29792.217946,0.000000
32,City of London,E09000001,314.942,24.546,T,"POLYGON ((-0.11155 51.51076, -0.11156 51.51091...",165,60,56291.301,569,19671.949,76816.335694,76816.335694,0.000000

In [52]:
# merge data sets
df = london_reprojected
df = pd.merge(df, road_stats_df, left_on="NAME", right_on="NAME", how="left")

In [ ]:
# calculate cycle routes ratio of total street network
df["TfL_cycle_ratio"] = df["TfL_cycle_routes_length_total"] / df["street_length_total"]